In [47]:
import pandas as pd
import numpy as np
import re
import matplotlib.pylab as plt
import seaborn as sns

from sklearn.preprocessing import LabelEncoder
from nltk.corpus import stopwords
# !pip install Counter
from collections import Counter
import string


plt.style.use('fivethirtyeight')

In [48]:
df=pd.read_csv("IMDB Dataset.csv")
df.shape

(50000, 2)

In [49]:
df

                                                  review sentiment
0      One of the other reviewers has mentioned that ...  positive
1      A wonderful little production. <br /><br />The...  positive
2      I thought this was a wonderful way to spend ti...  positive
3      Basically there's a family where a little boy ...  negative
4      Petter Mattei's "Love in the Time of Money" is...  positive
...                                                  ...       ...
49995  I thought this movie did a down right good job...  positive
49996  Bad plot, bad dialogue, bad acting, idiotic di...  negative
49997  I am a Catholic taught in parochial elementary...  negative
49998  I'm going to have to disagree with the previou...  negative
49999  No one expects the Star Trek movies to be high...  negative

[50000 rows x 2 columns]

In [50]:
# 1) Lowecasing: Simply use str operator
df['review']=df['review'].str.lower()
df

                                                  review sentiment
0      one of the other reviewers has mentioned that ...  positive
1      a wonderful little production. <br /><br />the...  positive
2      i thought this was a wonderful way to spend ti...  positive
3      basically there's a family where a little boy ...  negative
4      petter mattei's "love in the time of money" is...  positive
...                                                  ...       ...
49995  i thought this movie did a down right good job...  positive
49996  bad plot, bad dialogue, bad acting, idiotic di...  negative
49997  i am a catholic taught in parochial elementary...  negative
49998  i'm going to have to disagree with the previou...  negative
49999  no one expects the star trek movies to be high...  negative

[50000 rows x 2 columns]

In [51]:
# 2) Remove punctuation using a build in function:
punc=string.punctuation
print(punc)

!"#$%&'()*+,-./:;<=>?@[\]^_`{|}~

In [52]:
def remove_punctuation(para):
    for text in para:
        if text in punc:
            para=para.replace(text,'')
    return para

In [53]:
text1="My name is Arya. What is your name?"

res=remove_punctuation(text1)
print(res)

My name is Arya What is your name

In [54]:
df["review"].iloc[4] # So we can see that we have " " used here. Let's see if our fucntion can remove it

'petter mattei\'s "love in the time of money" is a visually stunning film to watch. mr. mattei offers us a vivid portrait about human relations. this is a movie that seems to be telling us what money, power and success do to people in the different situations we encounter. <br /><br />this being a variation on the arthur schnitzler\'s play about the same theme, the director transfers the action to the present time new york where all these different characters meet and connect. each one is connected in one way, or another to the next person, but no one seems to know the previous point of contact. stylishly, the film has a sophisticated luxurious look. we are taken to see how these people live and the world they live in their own habitat.<br /><br />the only thing one gets out of all these souls in the picture is the different stages of loneliness each one inhabits. a big city is not exactly the best place in which human relations find sincere fulfillment, as one discerns is the case with most of the people we encounter.<br /><br />the acting is good under mr. mattei\'s direction. steve buscemi, rosario dawson, carol kane, michael imperioli, adrian grenier, and the rest of the talented cast, make these characters come alive.<br /><br />we wish mr. mattei good luck and await anxiously for his next work.'

In [55]:
df["review"]=df["review"].apply(remove_punctuation) # .apply() is just like a for loop. It applies the same logic to the entire df
df

                                                  review sentiment
0      one of the other reviewers has mentioned that ...  positive
1      a wonderful little production br br the filmin...  positive
2      i thought this was a wonderful way to spend ti...  positive
3      basically theres a family where a little boy j...  negative
4      petter matteis love in the time of money is a ...  positive
...                                                  ...       ...
49995  i thought this movie did a down right good job...  positive
49996  bad plot bad dialogue bad acting idiotic direc...  negative
49997  i am a catholic taught in parochial elementary...  negative
49998  im going to have to disagree with the previous...  negative
49999  no one expects the star trek movies to be high...  negative

[50000 rows x 2 columns]

In [56]:
df["review"].iloc[4]

'petter matteis love in the time of money is a visually stunning film to watch mr mattei offers us a vivid portrait about human relations this is a movie that seems to be telling us what money power and success do to people in the different situations we encounter br br this being a variation on the arthur schnitzlers play about the same theme the director transfers the action to the present time new york where all these different characters meet and connect each one is connected in one way or another to the next person but no one seems to know the previous point of contact stylishly the film has a sophisticated luxurious look we are taken to see how these people live and the world they live in their own habitatbr br the only thing one gets out of all these souls in the picture is the different stages of loneliness each one inhabits a big city is not exactly the best place in which human relations find sincere fulfillment as one discerns is the case with most of the people we encounterbr br the acting is good under mr matteis direction steve buscemi rosario dawson carol kane michael imperioli adrian grenier and the rest of the talented cast make these characters come alivebr br we wish mr mattei good luck and await anxiously for his next work'

In [57]:
# 3) Convert the slang words to normal words:
abbreviations={
    "ASAP": "As Soon As Possible",
    "ATM": "At The Moment",
    "BTW": "By The Way",
    "DM": "Direct Message",
    "FAQ": "Frequently Asked Questions",
    "FOMO": "Fear Of Missing Out",
    "FYI": "For Your Information",
    "GN": "Good Night",
    "GOAT": "Greatest Of All Time",
}

In [58]:
def remove_slang(text):
    new_text=[]
    for word in text.split():
        if word.upper() in abbreviations:
            new_text.append(abbreviations[word.upper()])
        else:
            new_text.append(word)

    
    return " ".join(new_text)

In [59]:
test1="He is GOAT"
res=remove_slang(test1)
print(res)

He is Greatest Of All Time

In [ ]:
test1="Gn world,FYI, tomorrow is new year so dm asap"
res=remove_slang(test1)
print(res) # Since FYI is tokenized as FYI, it is not converted to it's keys

Good Night world,FYI, tomorrow is new year so Direct Message As Soon As Possible